"""S-parameter viewer layout, kept separate from parsing and plotting behavior."""
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QFormLayout,
    QPushButton, QListWidget, QComboBox, QLabel, QSplitter, QTabWidget,
    QPlainTextEdit, QTableView, QGroupBox, QScrollArea)
from matplotlib.figure import Figure
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg, NavigationToolbar2QT


def build_viewer(owner, modes):
    splitter = QSplitter(Qt.Orientation.Horizontal)
    splitter.setChildrenCollapsible(False)
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    scroll.setMinimumWidth(250)
    scroll.setMaximumWidth(390)
    panel = QWidget()
    panel.setObjectName('viewerSidebar')
    side = QVBoxLayout(panel)
    scroll.setWidget(panel)
    splitter.addWidget(scroll)
    actions = QHBoxLayout()
    owner.open_btn = QPushButton('打开 SNP / S2PX')
    owner.open_btn.setObjectName('primary')
    owner.open_btn.clicked.connect(owner.open_files)
    owner.paste_btn = QPushButton('粘贴')
    owner.paste_btn.clicked.connect(owner.paste)
    actions.addWidget(owner.open_btn)
    actions.addWidget(owner.paste_btn)
    side.addLayout(actions)
    side.addWidget(QLabel('数据列表 · 勾选显示，选中查看详情'))
    owner.files = QListWidget()
    owner.files.setMinimumHeight(140)
    owner.files.currentRowChanged.connect(owner.select)
    owner.files.itemChanged.connect(owner.plot)
    side.addWidget(owner.files, 1)
    row = QHBoxLayout()
    for title, slot in [('移除选中', owner.remove), ('清空', owner.clear_files)]:
        button = QPushButton(title)
        button.clicked.connect(slot)
        row.addWidget(button)
    side.addLayout(row)
    group = QGroupBox('比较与频率设置')
    form = QFormLayout(group)
    form.setRowWrapPolicy(QFormLayout.RowWrapPolicy.WrapAllRows)
    owner.overlay = QComboBox()
    owner.overlay.addItems(['叠加勾选文件', '仅查看选中文件'])
    owner.axis = QComboBox()
    owner.unit = QComboBox()
    owner.unit.addItems(['GHz', 'MHz', 'kHz', 'Hz'])
    owner.segment = QComboBox()
    owner.segment.addItem('全部')
    for label, widget in [('查看方式', owner.overlay), ('当前文件横轴', owner.axis),
                          ('频率单位', owner.unit), ('当前文件分段', owner.segment)]:
        form.addRow(label, widget)
        widget.currentIndexChanged.connect(owner.plot)
    note = QLabel('横轴与分段按文件分别设置。叠加前请确认 RF / IF 的物理含义一致。叠加不插值、不对齐点；差异计算另作唯一频点匹配。')
    note.setWordWrap(True)
    note.setStyleSheet('color: #64748b;')
    form.addRow(note)
    for title, slot in [('同名文件差异…', owner.compare_files),
                        ('任意文件差异 / 统计', owner.compare_any_files)]:
        button = QPushButton(title)
        button.clicked.connect(slot)
        form.addRow(button)
    side.addWidget(group)
    owner.export_btn = QPushButton('导出当前文件完整 CSV')
    owner.export_btn.clicked.connect(owner.export)
    owner.export_btn.setEnabled(False)
    side.addWidget(owner.export_btn)
    main = QWidget()
    content = QVBoxLayout(main)
    content.setContentsMargins(0, 0, 0, 0)
    owner.summary = QLabel('打开文件或粘贴数据开始查看；无需创建校准项目。')
    owner.summary.setWordWrap(True)
    owner.summary.setStyleSheet('background: white; border: 1px solid #dce3ec; padding: 10px;')
    content.addWidget(owner.summary)
    owner.warning = QLabel()
    owner.warning.setWordWrap(True)
    owner.warning.setStyleSheet('background: #fff7e6; color: #92400e; padding: 8px;')
    owner.warning.hide()
    content.addWidget(owner.warning)
    owner.tabs = QTabWidget()
    content.addWidget(owner.tabs, 1)
    page = QWidget()
    chart = QVBoxLayout(page)
    settings = QHBoxLayout()
    settings.addWidget(QLabel('显示'))
    owner.mode = QComboBox()
    owner.mode.addItems(modes)
    saved = owner.settings.value('mode', '幅度 (dB)')
    owner.mode.setCurrentText('解缠绕相位 (°)' if saved == '展开相位 (°)' else saved)
    owner.mode.currentIndexChanged.connect(owner.plot)
    settings.addWidget(owner.mode)
    owner.y_scale = QComboBox()
    owner.y_scale.addItems(['Y 轴 AutoScale', '手动范围…'])
    owner.y_scale.activated.connect(owner.change_y_scale)
    settings.addWidget(owner.y_scale)
    button = QPushButton('Y 轴设置…')
    button.clicked.connect(lambda: owner.edit_y_limits())
    settings.addWidget(button)
    settings.addStretch()
    chart.addLayout(settings)
    owner.figure = Figure(figsize=(9, 6), layout='constrained', facecolor='white')
    owner.canvas = FigureCanvasQTAgg(owner.figure)
    # Preserve PARAMS indexing while placing transmission at the top right.
    owner.axes = owner.figure.subplots(2, 2).ravel()[[0, 2, 1, 3]]
    owner.toolbar = NavigationToolbar2QT(owner.canvas, owner)
    chart.addWidget(owner.toolbar)
    chart.addWidget(owner.canvas, 1)
    owner.canvas.mpl_connect('motion_notify_event', owner.hover)
    owner.canvas.mpl_connect('button_press_event', owner.plot_context_menu)
    owner.tabs.addTab(page, '曲线 · 2 × 2')
    owner.table = QTableView()
    owner.table.setAlternatingRowColors(True)
    owner.tabs.addTab(owner.table, '数据表')
    owner.meta = QPlainTextEdit()
    owner.meta.setReadOnly(True)
    owner.tabs.addTab(owner.meta, '元数据 / Mixer 配置')
    owner.raw = QPlainTextEdit()
    owner.raw.setReadOnly(True)
    owner.tabs.addTab(owner.raw, '原始文本')
    splitter.addWidget(main)
    splitter.setSizes([290, 1040])
    return splitter
