"""S-parameter viewer layout, kept separate from parsing and plotting behavior."""
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QFormLayout,
    QPushButton, QListWidget, QComboBox, QLabel, QSplitter, QTabWidget,
    QPlainTextEdit, QTableView, QGroupBox, QScrollArea)
from matplotlib.figure import Figure
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg, NavigationToolbar2QT


def build_viewer(owner, modes):
    splitter = QSplitter(Qt.Orientation.Horizontal)
    splitter.setChildrenCollapsible(False)
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    scroll.setMinimumWidth(250)
    scroll.setMaximumWidth(390)
    panel = QWidget()
    panel.setObjectName('viewerSidebar')
    side = QVBoxLayout(panel)
    scroll.setWidget(panel)
    splitter.addWidget(scroll)
    actions = QHBoxLayout()
    owner.open_btn = QPushButton('打开 SNP / S2PX')
    owner.open_btn.setObjectName('primary')
    owner.open_btn.clicked.connect(owner.open_files)
    owner.paste_btn = QPushButton('粘贴')
    owner.paste_btn.clicked.connect(owner.paste)
    actions.addWidget(owner.open_btn)
    actions.addWidget(owner.paste_btn)
    side.addLayout(actions)
    side.addWidget(QLabel('共享文件库 · 选中查看单个文件'))
    owner.files = QListWidget()
    owner.files.setMinimumHeight(140)
    owner.files.currentRowChanged.connect(owner.select)
    side.addWidget(owner.files, 1)
    row = QHBoxLayout()
    for title, slot in [('移除选中', owner.remove), ('清空', owner.clear_files)]:
        button = QPushButton(title)
        button.clicked.connect(slot)
        row.addWidget(button)
    side.addLayout(row)
    group = QGroupBox('单文件频率设置')
    owner.single_controls = group
    form = QFormLayout(group)
    form.setRowWrapPolicy(QFormLayout.RowWrapPolicy.WrapAllRows)
    owner.axis = QComboBox()
    owner.unit = QComboBox()
    owner.unit.addItems(['GHz', 'MHz', 'kHz', 'Hz'])
    owner.segment = QComboBox()
    owner.segment.addItem('全部')
    for label, widget in [('当前文件横轴', owner.axis),
                          ('频率单位', owner.unit), ('当前文件分段', owner.segment)]:
        form.addRow(label, widget)
        widget.currentIndexChanged.connect(owner.plot)
    button = QPushButton('与另一文件比较…')
    button.clicked.connect(owner.compare_any_files)
    form.addRow(button)
    side.addWidget(group)
    owner.export_btn = QPushButton('导出当前文件完整 CSV')
    owner.export_btn.clicked.connect(owner.export)
    owner.export_btn.setEnabled(False)
    side.addWidget(owner.export_btn)
    main = QWidget()
    outer = QVBoxLayout(main)
    outer.setContentsMargins(0, 0, 0, 0)
    owner.analysis_tabs = QTabWidget()
    outer.addWidget(owner.analysis_tabs)
    single = QWidget()
    owner.analysis_tabs.addTab(single, '单文件查看')
    content = QVBoxLayout(single)
    content.setContentsMargins(0, 0, 0, 0)
    owner.summary = QLabel('打开文件或粘贴数据开始查看；无需创建校准项目。')
    owner.summary.setWordWrap(True)
    owner.summary.setStyleSheet('background: white; border: 1px solid #dce3ec; padding: 10px;')
    content.addWidget(owner.summary)
    owner.warning = QLabel()
    owner.warning.setWordWrap(True)
    owner.warning.setStyleSheet('background: #fff7e6; color: #92400e; padding: 8px;')
    owner.warning.hide()
    content.addWidget(owner.warning)
    owner.tabs = QTabWidget()
    content.addWidget(owner.tabs, 1)
    page = QWidget()
    chart = QVBoxLayout(page)
    settings = QHBoxLayout()
    settings.addWidget(QLabel('显示'))
    owner.mode = QComboBox()
    owner.mode.addItems(modes)
    saved = owner.settings.value('mode', '幅度 (dB)')
    owner.mode.setCurrentText('解缠绕相位 (°)' if saved == '展开相位 (°)' else saved)
    owner.mode.currentIndexChanged.connect(owner.plot)
    settings.addWidget(owner.mode)
    owner.y_scale = QComboBox()
    owner.y_scale.addItems(['Y 轴 AutoScale', '手动范围…'])
    owner.y_scale.activated.connect(owner.change_y_scale)
    settings.addWidget(owner.y_scale)
    button = QPushButton('Y 轴设置…')
    button.clicked.connect(lambda: owner.edit_y_limits())
    settings.addWidget(button)
    settings.addStretch()
    chart.addLayout(settings)
    owner.figure = Figure(figsize=(9, 6), layout='constrained', facecolor='white')
    owner.canvas = FigureCanvasQTAgg(owner.figure)
    # Preserve PARAMS indexing while placing transmission at the top right.
    owner.axes = owner.figure.subplots(2, 2).ravel()[[0, 2, 1, 3]]
    owner.toolbar = NavigationToolbar2QT(owner.canvas, owner)
    chart.addWidget(owner.toolbar)
    chart.addWidget(owner.canvas, 1)
    owner.canvas.mpl_connect('motion_notify_event', owner.hover)
    owner.canvas.mpl_connect('button_press_event', owner.plot_context_menu)
    owner.tabs.addTab(page, '曲线 · 2 × 2')
    owner.table = QTableView()
    owner.table.setAlternatingRowColors(True)
    owner.tabs.addTab(owner.table, '数据表')
    owner.meta = QPlainTextEdit()
    owner.meta.setReadOnly(True)
    owner.tabs.addTab(owner.meta, '元数据 / Mixer 配置')
    owner.raw = QPlainTextEdit()
    owner.raw.setReadOnly(True)
    owner.tabs.addTab(owner.raw, '原始文本')
    from comparison_page import ComparisonPage
    owner.comparison_view = ComparisonPage([], owner)
    owner.comparison_view.setWindowFlags(Qt.WindowType.Widget)
    owner.comparison_view.setMinimumSize(0, 0)
    compare_scroll = QScrollArea()
    compare_scroll.setWidgetResizable(True)
    compare_scroll.setWidget(owner.comparison_view)
    owner.analysis_tabs.addTab(compare_scroll, '双文件比较')
    owner.analysis_tabs.currentChanged.connect(
        lambda index: (group.setVisible(index == 0), owner.export_btn.setVisible(index == 0)))
    splitter.addWidget(main)
    splitter.setSizes([290, 1040])
    return splitter
